# Generated by Django 2.2.8 on 2019-12-15 00:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailygoals',
            name='entryDate',
            field=models.DateField(default=datetime.datetime(2019, 12, 15, 0, 0, 24, 857337, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dailynote',
            name='entryDate',
            field=models.DateField(default=datetime.datetime(2019, 12, 15, 0, 0, 24, 876919, tzinfo=utc)),
        ),
    ]
