# Generated by Django 2.2.8 on 2019-12-15 00:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_auto_20191215_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailygoals',
            name='entryDate',
            field=models.DateField(default=datetime.datetime(2019, 12, 15, 0, 9, 58, 207426, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dailynote',
            name='entryDate',
            field=models.DateField(default=datetime.datetime(2019, 12, 15, 0, 9, 58, 226988, tzinfo=utc), unique=True),
        ),
    ]
