# Generated by Django 2.2.8 on 2019-12-15 01:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_auto_20191215_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='maingoals',
            name='completeDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailygoals',
            name='entryDate',
            field=models.DateField(default=datetime.datetime(2019, 12, 15, 1, 12, 27, 354759, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dailynote',
            name='entryDate',
            field=models.DateField(default=datetime.datetime(2019, 12, 15, 1, 12, 27, 375001, tzinfo=utc), unique=True),
        ),
    ]
