# Generated by Django 2.2 on 2019-12-14 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='HabitType',
            new_name='HabitIsDecimal',
        ),
        migrations.AlterField(
            model_name='habit',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
