# Generated by Django 2.2 on 2019-12-14 00:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_auto_20191214_0603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='HabitIsDecimal',
            new_name='habitIsDecimal',
        ),
        migrations.RenameField(
            model_name='habitentrybool',
            old_name='HabitID',
            new_name='habit',
        ),
        migrations.RenameField(
            model_name='habitentrydecimal',
            old_name='HabitID',
            new_name='habitID',
        ),
        migrations.AddField(
            model_name='habitentrybool',
            name='entryDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='habitentrydecimal',
            name='entryDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
