# Generated by Django 2.2 on 2019-12-14 00:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_auto_20191214_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='creationDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
